CREATE DATABASE IF NOT EXISTS tiempo;
USE tiempo;

CREATE TABLE consultas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ciudad VARCHAR(100),
    tipo VARCHAR(50),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
